version: 2.1

orbs:
  node: circleci/node@4.7

executors:
  linux: # a Linux VM running Ubuntu 20.04
    machine:
      image: ubuntu-2004:202107-02

jobs:
  test:
    parameters:
      os:
        type: executor
      matrix-var:
        type: string
    executor: linux
    steps:
      - checkout
      - run:
          shell: bash
          command: echo "matrix vaule << parameters.matrix-var >> "
          name: step1

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              matrix-var: ["python", "java"]
