version: 2.1



executors:
  linux: # a Linux VM running Ubuntu 20.04
    machine:
      image: ubuntu-2004:202107-02

jobs:
 
  build:
      docker:
        # Primary Executor
        - image: openjdk:17.0

        # Dependency Service(s)
        - image: postgres:10.8
          environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
      steps:
        - checkout
        - run: echo "this is the build job"
  
  job1:
    executor:
      name: linux
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our context"
          command: |
            echo $MY_ENV_VAR
            
  test:
    parameters:
      matrix-var:
        type: string     
    executor:
      name: linux
    steps:
      - checkout
      - run:
          shell: bash
          command: echo "matrix vaule << parameters.matrix-var >> "
          name: step1

workflows:
  all-tests:
    jobs:
      - build
      - job1 :
          context: smaple-contex
      - test:
          matrix:
            parameters:
              matrix-var: ["python", "java"]
